// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.2
// source: regen/keystone/v1alpha1/account.proto

package support_service

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AccountServiceBootstrapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PubKey *anypb.Any `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
}

func (x *AccountServiceBootstrapRequest) Reset() {
	*x = AccountServiceBootstrapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_regen_keystone_v1alpha1_account_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountServiceBootstrapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountServiceBootstrapRequest) ProtoMessage() {}

func (x *AccountServiceBootstrapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_regen_keystone_v1alpha1_account_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountServiceBootstrapRequest.ProtoReflect.Descriptor instead.
func (*AccountServiceBootstrapRequest) Descriptor() ([]byte, []int) {
	return file_regen_keystone_v1alpha1_account_proto_rawDescGZIP(), []int{0}
}

func (x *AccountServiceBootstrapRequest) GetPubKey() *anypb.Any {
	if x != nil {
		return x.PubKey
	}
	return nil
}

type AccountServiceBootstrapResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountAddress string `protobuf:"bytes,1,opt,name=account_address,json=accountAddress,proto3" json:"account_address,omitempty"`
	KeyAddress     string `protobuf:"bytes,2,opt,name=key_address,json=keyAddress,proto3" json:"key_address,omitempty"`
}

func (x *AccountServiceBootstrapResponse) Reset() {
	*x = AccountServiceBootstrapResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_regen_keystone_v1alpha1_account_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountServiceBootstrapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountServiceBootstrapResponse) ProtoMessage() {}

func (x *AccountServiceBootstrapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_regen_keystone_v1alpha1_account_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountServiceBootstrapResponse.ProtoReflect.Descriptor instead.
func (*AccountServiceBootstrapResponse) Descriptor() ([]byte, []int) {
	return file_regen_keystone_v1alpha1_account_proto_rawDescGZIP(), []int{1}
}

func (x *AccountServiceBootstrapResponse) GetAccountAddress() string {
	if x != nil {
		return x.AccountAddress
	}
	return ""
}

func (x *AccountServiceBootstrapResponse) GetKeyAddress() string {
	if x != nil {
		return x.KeyAddress
	}
	return ""
}

var File_regen_keystone_v1alpha1_account_proto protoreflect.FileDescriptor

var file_regen_keystone_v1alpha1_account_proto_rawDesc = []byte{
	0x0a, 0x25, 0x72, 0x65, 0x67, 0x65, 0x6e, 0x2f, 0x6b, 0x65, 0x79, 0x73, 0x74, 0x6f, 0x6e, 0x65,
	0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x72, 0x65, 0x67, 0x65, 0x6e, 0x2e, 0x6b,
	0x65, 0x79, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31,
	0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4f, 0x0a, 0x1e, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x42, 0x6f, 0x6f,
	0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a,
	0x07, 0x70, 0x75, 0x62, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x41, 0x6e, 0x79, 0x52, 0x06, 0x70, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x22, 0x6b, 0x0a, 0x1f,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x42, 0x6f,
	0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x27, 0x0a, 0x0f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6b, 0x65, 0x79, 0x5f,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6b,
	0x65, 0x79, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x32, 0x90, 0x01, 0x0a, 0x0e, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x7e, 0x0a, 0x09,
	0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x12, 0x37, 0x2e, 0x72, 0x65, 0x67, 0x65,
	0x6e, 0x2e, 0x6b, 0x65, 0x79, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x38, 0x2e, 0x72, 0x65, 0x67, 0x65, 0x6e, 0x2e, 0x6b, 0x65, 0x79, 0x73, 0x74,
	0x6f, 0x6e, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x42, 0x6f, 0x6f, 0x74, 0x73,
	0x74, 0x72, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x33, 0x5a, 0x31,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65, 0x67, 0x65, 0x6e,
	0x2d, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x6b, 0x65, 0x79, 0x73, 0x74, 0x6f, 0x6e,
	0x65, 0x2f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_regen_keystone_v1alpha1_account_proto_rawDescOnce sync.Once
	file_regen_keystone_v1alpha1_account_proto_rawDescData = file_regen_keystone_v1alpha1_account_proto_rawDesc
)

func file_regen_keystone_v1alpha1_account_proto_rawDescGZIP() []byte {
	file_regen_keystone_v1alpha1_account_proto_rawDescOnce.Do(func() {
		file_regen_keystone_v1alpha1_account_proto_rawDescData = protoimpl.X.CompressGZIP(file_regen_keystone_v1alpha1_account_proto_rawDescData)
	})
	return file_regen_keystone_v1alpha1_account_proto_rawDescData
}

var file_regen_keystone_v1alpha1_account_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_regen_keystone_v1alpha1_account_proto_goTypes = []interface{}{
	(*AccountServiceBootstrapRequest)(nil),  // 0: regen.keystone.v1alpha1.AccountServiceBootstrapRequest
	(*AccountServiceBootstrapResponse)(nil), // 1: regen.keystone.v1alpha1.AccountServiceBootstrapResponse
	(*anypb.Any)(nil),                       // 2: google.protobuf.Any
}
var file_regen_keystone_v1alpha1_account_proto_depIdxs = []int32{
	2, // 0: regen.keystone.v1alpha1.AccountServiceBootstrapRequest.pub_key:type_name -> google.protobuf.Any
	0, // 1: regen.keystone.v1alpha1.AccountService.Bootstrap:input_type -> regen.keystone.v1alpha1.AccountServiceBootstrapRequest
	1, // 2: regen.keystone.v1alpha1.AccountService.Bootstrap:output_type -> regen.keystone.v1alpha1.AccountServiceBootstrapResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_regen_keystone_v1alpha1_account_proto_init() }
func file_regen_keystone_v1alpha1_account_proto_init() {
	if File_regen_keystone_v1alpha1_account_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_regen_keystone_v1alpha1_account_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountServiceBootstrapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_regen_keystone_v1alpha1_account_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountServiceBootstrapResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_regen_keystone_v1alpha1_account_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_regen_keystone_v1alpha1_account_proto_goTypes,
		DependencyIndexes: file_regen_keystone_v1alpha1_account_proto_depIdxs,
		MessageInfos:      file_regen_keystone_v1alpha1_account_proto_msgTypes,
	}.Build()
	File_regen_keystone_v1alpha1_account_proto = out.File
	file_regen_keystone_v1alpha1_account_proto_rawDesc = nil
	file_regen_keystone_v1alpha1_account_proto_goTypes = nil
	file_regen_keystone_v1alpha1_account_proto_depIdxs = nil
}
